### ISSUE TITLE
Optifine overlays appear on double slabs

### ISSUE THREAD

**Issue by WenXin20** [CJMinecraft01/DoubleSlabs#90]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Double Slabs v2.9.0`
`Optifine vHD U G1 pre30`

I created a resource pack that makes use of optifine's overlay textures, but when a double slab is created, all the different overlay textures are displayed at once. Is this something that can be fixed?

Resource Pack: [Minecraft Connected v1.5.zip](https://github.com/CJMinecraft01/DoubleSlabs/files/4976421/Minecraft.Connected.v1.5.zip)

![2020-07-25_15 43 53](https://user-images.githubusercontent.com/12000593/88466099-9d6bff80-ce8e-11ea-8598-202b7a3f0f93.png)

**Comment by CJMinecraft01** [comment]
Hi thanks for the report. Is this with every combination or only with wooden slab combinations?

**Comment by WenXin20** [comment]
It happens with every slab combination.

**Comment by CJMinecraft01** [comment]
Hmm. Very strange. I'm can't currently access my PC at the moment but when I'm back I'll try and have a go at fixing this 👍

**Comment by WenXin20** [comment]
Thanks! Much appreciated! The bug has been around since the early days of the mod, and I finally decided to report it since it makes it harder to build if I want to keep the texture pack.
The interesting thing is that connected textures work pretty well, such as with the smooth stone slab, except when the slabs are placed vertically.

**Comment by CJMinecraft01** [comment]
From looking into this further, it appears that OptiFine thinks that the double slab block is a block that blocks can connect to, but it is assuming so for all blocks. I'm not too sure how to go about fixing it as OptiFine doesn't have public released code but I'll continue to try my best :)

**Comment by WenXin20** [comment]
Thanks again!

**Comment by CJMinecraft01** [comment]
Hi! I just tested this today using the resource pack you sent and it appears to work fine. I used the default OptiFine settings. The only issue I noticed was with vertical stone slabs and how they connect but this could potentially be fixed by changing the model type to be lazy (using the client config)

**Comment by WenXin20** [comment]
Thanks! I'll give it a try.
What does it mean if I change it to lazy?

**Comment by CJMinecraft01** [comment]
In the client options there's a list of lazy models which use a technique where the slab itself is not rotated, but rather the texture of an already defined vertical slab is replaced

**Comment by WenXin20** [comment]
I'm still seeing these overlays, even when using the lazy model rendering.

**Comment by CJMinecraft01** [comment]
Are you using any other mods?

**Comment by WenXin20** [comment]
I just tried with only Optifine & Double Slabs and I still get this issue. It looks like by default Connected Textures is off and should be set to Fancy, which is found under the Quality button.
Then the game has to be restarted after applying the resource pack to see this issue.
Strangely enough, if I reload my textures, this issue goes away, but returns when I reload the game. But this isn't ideal for modpacks when reloading textures can take quite a while.

**Comment by CJMinecraft01** [comment]
I'm going to try and recreate this issue and to try and understand just what OptiFine is doing. Are these the only double slabs in the world? It could be that OptiFine is caching the value and updating it every time a new slab is combined and hence is giving the multiple connected textures but I'm not too certain.

**Comment by WenXin20** [comment]
It happens with any new slabs that I place as well, if the textures were not reloaded using F3+t. It's very strange.
Thanks!

**Comment by CJMinecraft01** [comment]
Would you mind testing this in the latest version to see if this issue still persists?

**Comment by WenXin20** [comment]
Hmm, looks like it still happens with v3.5.3, and connected textures aren't working either. I haven't used optifine in a while though, since I now use the ctm mod for connected textures. Although that has its own minor bug I'll create a separate issue for.

**Comment by CJMinecraft01** [comment]
Okay, I'm not too sure what else I can do to fix this unfortunately. I am no longer doing any hacky thing to make the slabs work, they are simply the vanilla models being combined. I'm wondering if there's anything that can be done on a resource pack side?

**Comment by WenXin20** [comment]
Yeah, I'm not sure. I haven't used optifine's CTM methods in quite a while. Maybe their wiki for it will help? https://github.com/sp614x/optifine/tree/master/OptiFineDoc/doc
